# This compose file is generic.
# If you would like to use it please change all volumes to point to
# correct locations on your Docker host.

# pjuu.com stores this configuration data along with other Infrastructure
# as Code.

version: "3"
services:
  pjuu:
    image: pjuu/pjuu:web
    deploy:
      restart_policy:
        condition: any
    container_name: pjuu
    volumes:
      - /host/data/pjuu:/data/conf
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis

  worker:
    image: pjuu/pjuu:worker
    deploy:
      restart_policy:
        condition: any
    volumes:
      - /host/data/pjuu:/data/conf
    links:
      - redis
      - mongo
    container_name: worker
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:3.2
    command: redis-server --appendonly yes
    deploy:
      restart_policy:
        condition: any
    container_name: redis
    volumes:
      - /host/data/redis:/data

  mongo:
    image: mongo:3.4
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 1G
    container_name: mongo
    volumes:
      - /host/data/mongo:/data/db

  nginx:
    image: nginx:1.12
    deploy:
      restart_policy:
        condition: any
    container_name: nginx
    links:
      - pjuu
    volumes:
      - /host/data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /host/data/nginx/ssl:/data/ssl:ro
      - /host/data/nginx/files:/data/files:ro
    ports:
      - "80:80"
      - "443:443"
